export const card_data=[
    {
        icon:"angular",
        title:"angular",
        sub_title:"",
        redirectLink:"angular",
    },
    {
        icon:"reactjs",
        title:"react.js",
        sub_title:"",
        redirectLink:"reactjs",
    },
    {
        icon:"vuejs",
        title:"vue.js",
        sub_title:"",
        redirectLink:"vuejs",
    },
    {
        icon:"expressjs",
        title:"express.js",
        sub_title:"",
        redirectLink:"expressjs",
    },
    {
        icon:"threejs",
        title:"three.js",
        sub_title:"",
        redirectLink:"threejs",
    },
    {
        icon:"django",
        title:"django",
        sub_title:"",
        redirectLink:"django",
    },
    {
        icon:"flask",
        title:"flask",
        sub_title:"",
        redirectLink:"flask",
    },
    {
        icon:"git",
        title:"git",
        sub_title:"",
        redirectLink:"git-hacks",
    },
    {
        icon:"linux",
        title:"linux",
        sub_title:"",
        redirectLink:"basic-linux",
    },
    {
        icon:"cloud",
        title:"cloud",
        sub_title:"",
        redirectLink:"cloud-services",
    },
    {
        icon:"devops",
        title:"devops",
        sub_title:"",
        redirectLink:"devops",
    },
    {
        icon:"deeplearning",
        title:"deep learning",
        sub_title:"",
        redirectLink:"deeplearning",
    },
    {
        icon:"machinelearning",
        title:"machine learning",
        sub_title:"",
        redirectLink:"machinelearning",
    },
    {
        icon:"numpy",
        title:"numpy",
        sub_title:"",
        redirectLink:"numpy",
    },
    {
        icon:"pandas",
        title:"pandas",
        sub_title:"",
        redirectLink:"pandas",
    },
    {
        icon:"js",
        title:"vanilla javascript",
        sub_title:"",
        redirectLink:"javascript-tips",
    },
    {
        icon:"interview",
        title:"js interview prep",
        sub_title:"",
        redirectLink:"interview-preparation",
    },
    {
        icon:"datastructures",
        title:"data structures",
        sub_title:"",
        redirectLink:"datastructures",
    },
    {
        icon:"css",
        title:"awesome css hacks",
        sub_title:"",
        redirectLink:"cssprojects",
    },
    {
        icon:"opencv",
        title:"opencv with python",
        sub_title:"",
        redirectLink:"opencv",
    },
    {
        icon:"python",
        title:"python tips and tricks",
        sub_title:"",
        redirectLink:"python-tips",
    },
    {
        icon:"projects",
        title:"projects on angular",
        sub_title:"",
        redirectLink:"angular-projects",
    },
    {
        icon:"projects",
        title:"projects on react.js",
        sub_title:"",
        redirectLink:"reactjs-projects",
    },
    {
        icon:"projects",
        title:"projects on vue.js",
        sub_title:"",
        redirectLink:"vuejs-projects",
    },
    {
        icon:"projects",
        title:"projects on three.js",
        sub_title:"",
        redirectLink:"threejs-projects",
    },
    {
        icon:"projects",
        title:"projects on python",
        sub_title:"",
        redirectLink:"python-projects",
    },
    {
        icon:"mysql",
        title:"mysql",
        sub_title:"",
        redirectLink:"mysql-tips",
    },
    {
        icon:"mongodb",
        title:"mongo db",
        sub_title:"",
        redirectLink:"mongo-tips",
    },
    {
        icon:"interview",
        title:"angular interview prep",
        sub_title:"",
        redirectLink:"interview-preparation",
    },
    {
        icon:"interview",
        title:"react.js interview prep",
        sub_title:"",
        redirectLink:"interview-preparation",
    },
    {
        icon:"interview",
        title:"clone projects",
        sub_title:"",
        redirectLink:"clone-projects",
    },
    {
        icon:"gadgets",
        title:"awesome gadgets",
        sub_title:"",
        redirectLink:"gadgets",
    },
    {
        icon:"howto",
        title:"learn how to ",
        sub_title:"",
        redirectLink:"how-to",
    },
    {
        icon:"generalknowledge",
        title:"general knowledge",
        sub_title:"",
        redirectLink:"generalknowledge",
    },
    {
        icon:"front-end",
        title:"front-end hacks",
        sub_title:"",
        redirectLink:"front-end-hacks",
    },
    {
        icon:"blogs",
        title:"blogs",
        sub_title:"",
        redirectLink:"blogs",
    },
    {
        icon:"communityforum",
        title:"community forum",
        sub_title:"",
        redirectLink:"communityforum",
    },
    {
        icon:"resources",
        title:"resources",
        sub_title:"",
        redirectLink:"resources",
    }
]