export const card_data=[
    {
        icon:"",
        title:"angular",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"react.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"vue.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"express.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"three.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"django",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"flask",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"git",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"linux",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"cloud",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"devops",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"deep learning",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"machine learning",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"numpy",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"pandas",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"vanilla javascript",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"js interview prep",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"data structures",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"awesome css hacks",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"opencv with python",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"python tips and tricks",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"mini projects on angular",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"mini projects on react.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"mini projects on vue.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"mini projects on three.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"mysql",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"mongo db",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"angular interview prep",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"react.js interview prep",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"clone projects",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"awesome gadgets",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"learn how to ",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"general knowledge",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"front-end hacks",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"blogs",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"community forum",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"",
        title:"resources",
        sub_title:"",
        redirectLink:"",
    }
]