export const card_data=[
    {
        icon:"angular",
        title:"angular",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"reactjs",
        title:"react.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"vuejs",
        title:"vue.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"expressjs",
        title:"express.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"threejs",
        title:"three.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"django",
        title:"django",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"flask",
        title:"flask",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"git",
        title:"git",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"linux",
        title:"linux",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"cloud",
        title:"cloud",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"devops",
        title:"devops",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"deeplearning",
        title:"deep learning",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"machinelearning",
        title:"machine learning",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"numpy",
        title:"numpy",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"pandas",
        title:"pandas",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"js",
        title:"vanilla javascript",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"interview",
        title:"js interview prep",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"datastructures",
        title:"data structures",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"css",
        title:"awesome css hacks",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"opencv",
        title:"opencv with python",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"python",
        title:"python tips and tricks",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"projects",
        title:"mini projects on angular",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"projects",
        title:"mini projects on react.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"projects",
        title:"mini projects on vue.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"projects",
        title:"mini projects on three.js",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"mysql",
        title:"mysql",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"mongodb",
        title:"mongo db",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"interview",
        title:"angular interview prep",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"interview",
        title:"react.js interview prep",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"interview",
        title:"clone projects",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"gadgets",
        title:"awesome gadgets",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"howto",
        title:"learn how to ",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"generalknowledge",
        title:"general knowledge",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"front-end",
        title:"front-end hacks",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"blogs",
        title:"blogs",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"communityforum",
        title:"community forum",
        sub_title:"",
        redirectLink:"",
    },
    {
        icon:"resources",
        title:"resources",
        sub_title:"",
        redirectLink:"",
    }
]